ApiBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: ApiBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        available:
            type: boolean
        price:
            type: integer
        salePrice:
            type: integer
            nullable: true
            column: sale_price
    lifecycleCallbacks: {  }
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: product

    manyToMany:
        categories:
            targetEntity: Category