ApiBundle\Entity\Region:
    type: entity
    table: null
    repositoryClass: ApiBundle\Repository\RegionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        cities:
            targetEntity: City
            mappedBy: region
