admin_dashboard:
    path:     /
    defaults: { _controller: AdminBundle:Dashboard:index }

admin_product:
    path:     /product
    defaults: { _controller: AdminBundle:Product:index }


admin_product_get:
    path:     /product/view/{id}
    defaults: { _controller: AdminBundle:Product:get }
    requirements:
        id: '\d+'