admin_homepage_dashboard:
    path:     /
    defaults: { _controller: AdminBundle:Dashboard:index }

admin_homepage_product:
    path:     /product
    defaults: { _controller: AdminBundle:Product:index }
