
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /
