
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    host: admin.eshop.com


shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    host: eshop.com
    prefix:   /

api_bundle:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api
