api_homepage_default:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_homepage:
    path:     /{path}
    defaults: { _controller: ApiBundle:Default:index }
    requirements:
        path: "^(?!img|api|build|test).+"