<?php

namespace ApiBundle\Repository;

/**
 * ClassAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
