<?php

namespace ApiBundle\Repository;

/**
 * ProductClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductClassRepository extends \Doctrine\ORM\EntityRepository
{
}
